Repository SOPT-all/35-COLLABORATION-ANDROID-YES24TICKET, pull requests merged in 2024-11, with the labels that each got.

#1 [init] 프로젝트 기초 세팅
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/androidTest/java/org/andsopt/android/yes24ticket/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/andsopt/android/yes24ticket/MainActivity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/Yes24TicketApp.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/local/DummyLocalDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/DummyRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasourceImpl/local/DummyLocalDataSourceImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasourceImpl/remote/DummyRemoteDataSourceImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/request/RequestDummyDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseDummyDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/DummyRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/DummyService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/DataSourceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RepositoryModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RetrofitModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/ServiceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/DummyIdEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/DummyNameEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/DummyRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/model/RouteModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/type/BottomNavigationType.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/DummyComponent.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyUiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/TicketReservationScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Color.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Theme.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Type.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/base/BaseResponse.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/constants/ApiConstants.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/context/ContextExt.kt
  app/src/test/java/org/andsopt/android/yes24ticket/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🩷INIT🩷

#5 [init] Typography 기초세팅
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Type.kt
  app/src/main/res/font/apple_sd_gothic_neo_bold.ttf
  app/src/main/res/font/apple_sd_gothic_neo_extrabold.ttf
  app/src/main/res/font/apple_sd_gothic_neo_medium.ttf
  app/src/main/res/font/apple_sd_gothic_neo_regular.ttf
  app/src/main/res/font/apple_sd_gothic_neo_semibold.ttf
  gradle/libs.versions.toml
Labels: 🩷INIT🩷

#11 [init] 색상 및 테마 적용
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Color.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/ColorScheme.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Theme.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Type.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Yes24TicketTheme.kt
Labels: 🩷INIT🩷

#12 [refactor] Navigation : Serialization 적용
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/model/RouteModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
Labels: ✨REFACTOR✨

#10 [feat] Information Footer 컴포넌트 구현
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/InformationFooter.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#19 [feat] TopAppBar 컴포넌트 구현
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/Yes24TopAppBar.kt
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#16 [feat] FAB 공통컴포넌트 구현
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/FloatingButton.kt
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#17 [feat] 바텀 네비게이션 구현
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/model/RouteModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/type/BottomNavigationType.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/compose/ComposeExt.kt
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#24 [fix] file 이름 변경 , TopAppBar 일부 수정
  app/build.gradle.kts
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/ScrollToTopFloatingButton.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/Yes24TopAppBar.kt
  gradle/libs.versions.toml
Labels: 🛠️FIX🛠️

#25 [fix] 바텀 네비게이션 구조 및 서버 통신 로직 수정
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/DummyRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasourceImpl/remote/DummyRemoteDataSourceImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseDummyExampleDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/DummyRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/DummyService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/DummyEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/DummyRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyUiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/dummy/state/DummyYes24UiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/view/LoadState.kt
Labels: 🛠️FIX🛠️

#28 [feat] 예매하기 뷰
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseTicketAvailableTimesDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseTimeSlotsDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TicketAvailableTimesEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TimeSlotsEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/TicketReservationRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/TicketReservationScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/CalendarDayOfWeeksRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/CalendarDaysRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/CalendarMonthRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/CalendarView.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/ReservationProgressRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/ReservationTitleRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/SeatItem.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/SelectConcertTimeView.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/SelectTimeButton.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/viewmodel/TicketReservationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#29 [feat] 홈 뷰 구현하기
  app/build.gradle.kts
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/AdBannerEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/LiveTicketRankingEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/MainBannerEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/WhatsHotEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/type/HomeCategoryType.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/component/Yes24TopAppBar.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/AdDisplayedHorizontalPager.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/BannerPageIndicator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/HeadDisplayedHorizontalPager.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/LiveTicketRankingLazyRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/SectionHeaderWithBlueArrow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/compose/ComposeExt.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🍀FEAT🍀

#30 [feat] 티켓 상세 뷰 구현
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TicketDetailEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TicketPricingEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/type/TicketSeatType.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/component/TicketDetailBox.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/component/TicketDetailExpandableRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/component/TicketDetailReserveButton.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/component/TicketDetailSeatAndTime.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/navigation/TicketDetailNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/state/TicketDetailExpandableState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/state/TicketDetailHeartState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/Color.kt
  app/src/main/java/org/andsopt/android/yes24ticket/ui/theme/ColorScheme.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/compose/ComposeExt.kt
  app/src/main/res/drawable/ic_arrow_up_16.xml
  app/src/main/res/values/strings.xml
Labels: 🍀FEAT🍀

#38 [feat] 홈 API 연결
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/HomeRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseAdBannerListDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseMainBannerListDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseTicketRankingListDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseWhatsHotListDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/HomeRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/HomeService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RepositoryModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/ServiceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/AdBannerEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/LiveTicketRankingEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/MainBannerEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/WhatsHotEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/HomeRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/AdDisplayedHorizontalPager.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/HeadDisplayedHorizontalPager.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/component/LiveTicketRankingLazyRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/state/HomeUiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/constants/ApiConstants.kt
Labels: 🍀FEAT🍀

#36 [feat] 카테고리 상세 뷰 API 연결
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/CategoryRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseCategoryDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/CategoryRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/CategoryService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RepositoryModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/ServiceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/CategoryRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/state/CategoryDetailState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/state/CategoryDetailUiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/constants/ApiConstants.kt
Labels: 🍀FEAT🍀

#32 [feat] 예매하기 뷰 API 연결
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/TicketingRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/request/RequestTimeSlotsDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/TicketingRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/TicketingService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RepositoryModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/ServiceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TimeSlotsDataEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/TicketingRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/CalendarView.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/viewmodel/TicketReservationViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/constants/ApiConstants.kt
Labels: 🍀FEAT🍀

#37 [feat] 티켓 상세 뷰 API 연결
  app/src/main/java/org/andsopt/android/yes24ticket/data/datasource/remote/TicketRemoteDataSource.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseTicketDetailDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/dto/response/ResponseTicketDetailLikeDto.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/repositoryImpl/TicketRepositoryImpl.kt
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/TicketService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/RepositoryModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/di/ServiceModule.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TicketDetailEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/model/TicketDetailLikeEntity.kt
  app/src/main/java/org/andsopt/android/yes24ticket/domain/repository/TicketRepository.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/state/TicketDetailHeartState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/state/TicketDetailUiState.kt
  app/src/main/java/org/andsopt/android/yes24ticket/util/constants/ApiConstants.kt
Labels: 🍀FEAT🍀

#40 [feat] 전체 뷰 연결
  app/src/main/java/org/andsopt/android/yes24ticket/data/service/TicketingService.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/CategoryDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/category/navigation/CategoryDetailNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/TicketDetailViewModel.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/component/TicketDetailReserveButton.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/detail/navigation/TicketDetailNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/TicketReservationRoute.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/TicketReservationScreen.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/ReservationProgressRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/component/ReservationTitleRow.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/navigation/TicketReservationNavigation.kt
  app/src/main/java/org/andsopt/android/yes24ticket/presentation/ui/ticket/reservation/viewmodel/TicketReservationViewModel.kt
Labels: 🍀FEAT🍀
